const countries = {
    "ru-RU":"Russian",
    "am-ET":"Amharic",
    "ar-SA": "Arabic",
    "be-BY": "Bielarus",
    "Bem-ZM": "Bemba",
    "bjs-BB": "Bajan",
    "bn-IN": "Bengali",
    "bo-CN": "Tibetan",
    "br-Ba": 'Bosnian',
    "ca-Es": "Catalan",
    "cop-EG": "Coptic",
    "cs-CZ": "Czech",
    "cy-GB": "Welsh",
    "da-DK": "Danish",
    "dz-BT": "Dzongkha",
    "de-DE": "German",
    "Dv-MV": "Madivian",
    "el-GR": "Greek",
    "en-GB": "English",
    "es-ES": "Spanish",
    "et-EE": "Estonion",
    "eu-ES": "Basque",
    "fa-IR": "Persian",
}